### ISSUE TITLE
Divisão de papeis

### ISSUE THREAD

**Issue by gabifranklin** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e1-proj-web-t7-pucalm#13]
- Scrum Master: Willams Andrade Lima
- Product Owner: Lucas Campos de Abreu
- Equipe de Desenvolvimento: Camyla Gomes Soares Oliveira, Gabriel Coutinho Rolim, Gabriela Franklin Sá de Moura, Lucas Campos de Abreu, Otávio Martins Ferreira, Rafael Costa Souza e Willams Andrade Lima
- Designer de UI/UX: Rafael Costa Souza
- Kanban Manager: Gabriela Franklin Sá de Moura
- Testador de Qualidade (QA): Camyla Gomes Soares Oliveira
- Gerente de Controle de Versão: Gabriel Coutinho Rolim

**Comment by willamsandradelima** [comment]
Podemos ter a @gabifranklin como um cargo de Kanban?
Kanban manager: Gabriela Franklin Sá de Moura

**Comment by LucasCdeAbreu** [comment]
@willamsandradelima,  Como sugestão, o acham de a  @GabrielC0ut pegar o posto de Gerente de Controle de Versão ? (Só para não criarmos um cargo "não oficial".)
Ficaria responsável pelo GitHub (que nesse caso é praticamente cuidar do Kanban e subir as versões mais atualizadas dos arquivos)

**Comment by gabifranklin** [comment]
Precisamos destacar um nome ou alguém para cada tarefa como um líder, mesmo para a equipe de desenvolvimento.
