### ISSUE TITLE
Alterar referências

### ISSUE THREAD

**Issue by gabifranklin** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e1-proj-web-t7-pucalm#25]
As referências devem sair do 01-Documentação de Contexto.md e passar para o documento de 09-Referências Bibliográficas.md

**Comment by gabifranklin** [comment]
Eu alterei as referências de local, se vocês puderem dar uma olhada.
Eu pus aqui o issue pra ficar registrado.

**Comment by willamsandradelima** [comment]
Há uma referência **que veio com o texto do professor** no item 03. Temos que validar isso porque não a temos em nossas referêcias.
