### ISSUE TITLE
Wireframes

### ISSUE THREAD

**Issue by gabifranklin** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e1-proj-web-t7-pucalm#4]
- [x] Esboço para telas
- [x] Validação com o user flow
- [x] Pequeno texto na documentação do GitHub, Item 04.
- [x] #24
- [x] Corrigir o Fluxo de usuário colocando fundo branco e uma borda diferente pra ação, para diferenciar do quadrado da página 
- [x] Alterar o nome do botão de “entrar” para “explorar”

**Comment by LucasCdeAbreu** [comment]
Só falta incluir o campo de "Comentários" ou "Feedbacks" na Landing Page, para atendermos o requisito funcional RF-03
